server:
  port: 7003
  error:
    include-message: always
spring:
  application:
    name: review-service

logging:
  level:
    root: INFO
    edu.learning: DEBUG

---
spring:
  config:
    activate:
      on-profile:
        - docker
server:
  port: 8080
