logging:
  level:
    org:
      springframework:
        boot: DEBUG

spring:
  application:
    name: email scheduler
  datasource:
    url: jdbc:postgresql://localhost:5432/qartz_demo
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: ALWAYS
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

quartz:
  job-store:
    class: org.quartz.impl.jdbcjobstore.JobStoreTX
    driver-delegate-class: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
    use-properties: true