server:
  port: 7002
  error:
    include-message: ALWAYS
logging:
  level:
    root: INFO
    edu:
      learning:
        microservices: DEBUG
spring:
  application:
    name: recommendation-service