spring:
  application:
    name: product-service
  config:
    activate:
      on-profile: docker
server:
  port: 8080

logging:
  level:
    root: INFO
    edu:
      learning:
        microservices: DEBUG