spring:
  application:
    name: ${APP_NAME:EazyBankApplication}
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS})%blue(%-5level)%red([%thread])%yellow(%logger{15})-%msg%n}