server:
  port: 7004
  error:
    include-message: always
spring:
  application:
    name: product-composite-service
  config:
    import:
      - swagger.yml

app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003

logging:
  level:
    org:
      springframework: DEBUG
    root: INFO
    edu.learning: DEBUG

---
spring:
  config:
    activate:
      on-profile:
        - docker
    import:
      - swagger.yml
server:
  port: 8080


app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080
