server:
  port: 7000
  error:
    include-message: ALWAYS
spring:
  application:
    name: product-composite-service
logging:
  level:
    root: INFO
    edu:
      learning: DEBUG
app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003
