spring:
  thymeleaf:
    cache: true
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:mem:tacocloud
    username: user
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG