spring:
  application:
    name: microservices/review-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: password
    hikari:
      initialization-fail-timeout: 60000



server:
  port: 7003
  error:
    include-message: always

logging:
  level:
    root: INFO
    edu.learning: DEBUG


---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql/review-db

server:
  port: 8080

