spring:
  application:
    name: microservices/product-service
  data:
    mongodb:
      auto-index-creation: true

server:
  port: 7001
  error:
    include-message: always

logging:
  level:
    root: INFO
    edu.learning: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

